name: Deployment

on:
  push:
    tags:
      - '**[0-9]+.[0-9]+.[0-9]+*'
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') &&
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v'))
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 2222
        command_timeout: 30m
        script: |
          cd ~/web/SeptaPlusPlus
          docker compose down
          git pull origin main
          docker build -t septaplusplus:latest .
          docker compose up -d
